spring:
  datasource:
    url: jdbc:mysql://localhost:3306/layui
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/templates


logging:
  level:
    cn.qqhxj.demo: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml